version: "2.0"
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9400:9200
  kibana:
    # image: kibana
    build: .
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
